name: DropSpawner
version: ${project.version}
api-version: 1.16
author: creatorfromhell, KarlofDuty, Warriorrrr
website: https://earthmc.net
main: com.karlofduty.dropspawner.DropSpawner
permissions:
  dropspawner.allowdrop:
    description: Lets a player use the plugin. Given by default.
    default: true